[tool.poetry]
name = "scratch"
version = "0.1.0"
description = ""
authors = ["krissmedt <kristoffer@smedt.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
